project_id = "pczmdbpmuovpxqeglfyn"

[functions.create-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.get-users-admin]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.primeiro-escritorio]
verify_jwt = false

[functions.manage-office]
verify_jwt = false

[functions.office-server]
verify_jwt = false

[functions.btg-create-ir-charge]
verify_jwt = true

[functions.btg-ir-webhook]
verify_jwt = false
